<a href="https://colab.research.google.com/github/Riyaz127/TNS-Practice/blob/main/Batch2_day08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#create a numpy array using arange arr from 1-20
import numpy as np
arr=np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#create an array of all with zeros with 10 elements
b=np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# create an array of all ones with 8 elements
c=np.ones(8)
print(c)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# create an array containing even numbers from 2-20
import numpy as np
d=np.arange(2,21,2)
print(d)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# create an array find number of dimentions,reshape,size
e=np.array([2,3,8,9,10,67,3,6,7,8])
print(np.ndim(e))
print(np.shape(e))
print(np.size(e))

1
(10,)
10


In [ ]:
# Multiply every element by 2
f=np.array([2,34,7,9,56,38,12,29])
print(f*2)

[  4  68  14  18 112  76  24  58]


In [ ]:
# find the square of every element
g=np.array([1,2,3,4,5,6,7,8,9,10])
print(g**2)

[  1   4   9  16  25  36  49  64  81 100]


In [ ]:
# divide every element by 10.
h=np.array([23,56,89,35,100])
print(h/10)

[ 2.3  5.6  8.9  3.5 10. ]


In [ ]:
# create 1D array and find sum,mean,max,min
i=np.array([12,67,29,37,57,44])
print("Sum:",np.sum(i))
print("mean:",np.mean(i))
print("max:",np.max(i))
print("min:",np.min(i))

Sum: 246
mean: 41.0
max: 67
min: 12


In [ ]:
# create 2 arrays and concatinate both arrays
j=np.arange(6)
k=np.array([23,7,9,34])
l=np.concatenate((j,k))
print(l)

[ 0  1  2  3  4  5 23  7  9 34]


In [ ]:
# create
df=np.linspace(1,2,4)
print(df)

[1.         1.33333333 1.66666667 2.        ]


In [ ]:
data=(np.random.rand(3,2)*10).astype(int)
print(data)

[[4 3]
 [3 1]
 [9 5]]
