<a href="https://colab.research.google.com/github/Riyaz127/TNS-Practice/blob/main/Batch2_Day15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Revision:


In [1]:
#1.Create a numpy array containing the numbers 10,20,30,40,50.
import numpy as np
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [6]:
#2. Create a 2x3 array containing the numbers from 1 to 6.
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)

2


In [20]:
#3. Create a 3x3 array of zeros.
c=np.zeros([3,3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
#4. create a 2x4 array of ones.
d=np.ones([2,4])
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
# 5.Create an array containing numbers from 1 to 10.
e=np.arange(1,11)
print(e)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
#6.Find the total numbers of Elements in the array.
print("Total numbers in the array is :",e.size)

Total numbers in the array is : 10


In [24]:
#7.Find the data type of array.
print("data type of e :",e.dtype)

data type of e : int64


In [25]:
#8.Find the length of the array.
print("length of the array e:",len(e))

length of the array e: 10


In [26]:
#9.Print the elements from index 1 to index 4.
print("Elements from index 1 to 4 :",e[1:4])

Elements from index 1 to 4 : [2 3 4]


In [27]:
#10.Create an array from 1 to 12 and reshape it into a 3x4 matrix.
f=np.arange(1,13)
d=f.reshape(3,4)
print(f,"\n")
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
